name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build APK with Pre-configured Kivy Docker Environment
      run: |
        buildozer init
        sed -i 's/android.api = 33/android.api = 31/' buildozer.spec
        sed -i 's/android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3==3.10.12,kivy==2.3.0,requests/' buildozer.spec
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sweety-APK
        path: bin/*.apk
        
